import { Type } from 'class-transformer';
import {
  IsArray,
  IsIn,
  IsOptional,
  IsString,
  MaxLength,
  ValidateNested,
} from 'class-validator';
import type { RiskLevel } from '../../generated/prisma/enums.js';

const RISK_LEVELS = ['INFORMATIONAL', 'LOW', 'MEDIUM', 'HIGH', 'CRITICAL'] as const;

export class ToolUsageDto {
  @IsString() toolId!: string;
  @IsString() name!: string;
  @IsString() status!: string;
  @IsOptional() @IsString() summary?: string;
  @IsOptional() @IsIn(RISK_LEVELS) risk?: RiskLevel;
}

/** One completed exchange: the question asked and the answer TANIA produced. */
export class RecordTurnDto {
  /** Message id generated by the Brain, kept so traces line up across systems. */
  @IsOptional() @IsString() @MaxLength(64) messageId?: string;

  @IsString() @MaxLength(8000) question!: string;

  @IsString() @MaxLength(60000) answer!: string;

  @IsOptional() @IsString() @MaxLength(32) intent?: string;

  @IsOptional() @IsIn(RISK_LEVELS) risk?: RiskLevel;

  @IsOptional() @IsString() @MaxLength(120) model?: string;

  /** Citations shown with the answer. */
  @IsOptional() @IsArray() evidence?: unknown[];

  /** Safe execution status only — never chain-of-thought. */
  @IsOptional() @IsArray() trace?: unknown[];

  @IsOptional()
  @IsArray()
  @ValidateNested({ each: true })
  @Type(() => ToolUsageDto)
  tools?: ToolUsageDto[];
}
